version: '3.8'

services:
  cassandra-server:
    image: cassandra:3.11
    container_name: cassandra-isi
    networks:
      - cassandra-net
    ports:
      - "9042:9042" 
    environment:
      - CASSANDRA_CLUSTER_NAME=MiClusterUniversitario
    volumes:
      - ./data:/var/lib/cassandra

networks:
  cassandra-net:
    driver: bridge